spring.data.mongodb:
  host: ${MONGO_HOST:localhost}
  port: ${MONGO_PORT:27017}
  database: ${MONGO_DB_NAME}
  username: ${MONGO_USERNAME}
  password: ${MONGO_PASSWORD}
  authentication-database: ${MONGO_AUTH_DB}

measurements:
  allowed-origins:
    - http://localhost:8080
    - http://localhost:5173
  allowed-methods: GET, POST, PUT, DELETE