version: '3.7'

services:
  mongodb:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: 
      MONGO_INITDB_ROOT_PASSWORD: 
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db
      
  measurements-api:
    image: measurements-api:0.0.1-SNAPSHOT
    restart: always
    environment:
      MONGO_HOST: mongodb
      MONGO_PORT: 27017
      MONGO_DB_NAME: measurements
      MONGO_USERNAME: 
      MONGO_PASSWORD: 
      MONGO_AUTH_DB: admin
    ports:
      - 8080:8080
    depends_on:
      - mongodb

volumes:
  mongodb_data_container: